import { useState } from "react";
import Head from "next/head";
import {
  Container,
  Row,
  Col,
  Form,
  FormGroup,
  Label,
  Input,
  Button,
} from "reactstrap";
import loginBannerImg from "../public/images/login-banner.jpg";
import Image from "next/image";
import toast, { Toaster } from "react-hot-toast";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);

  // login component
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    const form = e.target;
    const formData = new FormData(form);

    try {
      const email = formData.get("email");
      const password = formData.get("password");

      const response = await fetch("http://localhost:4000/api/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ email, password }),
      });

      if (response.ok) {
        const data = await response.json();
        const { token } = data;

        // Save the token to localStorage
        localStorage.setItem("token", token);

        // Redirect to the next screen upon successful login
        // For example, using next/router
        router.push("/car-request");
      } else {
        // Handle login error
        toast.error("Invalid Credentials");
        console.error("Login failed");
      }
    } catch (error) {
      toast.error("Login Failed");
      console.error("Login failed", error);
    }
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Car Selling App - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="login-section">
          <Row className="w-100 m-0">
            <Col md={6}>
              <div className="login-box">
                <div className="login-form">
                  <h2 className="text-center">
                    Login<i className="bi bi-car-front mx-2"></i>
                  </h2>
                  <Form className="mb-3" onSubmit={handleSubmit}>
                    <FormGroup>
                      <Label for="email">Email</Label>
                      <div className="d-flex align-items-center input-box">
                        <i className="bi bi-envelope-fill email-icon"></i>
                        <Input
                          type="email"
                          name="email"
                          id="email"
                          required
                          className="car-selling-input"
                          placeholder="Enter your email"
                        />
                      </div>
                    </FormGroup>
                    <FormGroup>
                      <Label for="password">Password</Label>
                      <div className="d-flex align-items-center input-box">
                        <i className="bi bi-lock-fill lock-icon"></i>
                        <Input
                          type={!showPassword ? "password" : "text"}
                          name="password"
                          id="password"
                          required
                          className="car-selling-input"
                          placeholder="Enter your password"
                        />
                        {!showPassword ? (
                          <div onClick={() => setShowPassword(!showPassword)}>
                            <i className="bi bi-eye-slash-fill lock-icon"></i>
                          </div>
                        ) : (
                          <div onClick={() => setShowPassword(!showPassword)}>
                            <i className="bi bi-eye-fill lock-icon"></i>
                          </div>
                        )}
                      </div>
                    </FormGroup>
                    <div className="text-center">
                      <Button
                        disabled={loading}
                        type="submit"
                        className="login-btn"
                      >
                        {loading ? "Loading..." : "Login"}
                      </Button>
                    </div>
                  </Form>
                  <small className="mt-3">
                    <strong>Hint</strong>
                    <br />
                    User Name: Amjad@desolint.com <br />
                    Password: 123456abc
                  </small>
                </div>
              </div>
            </Col>
            <Col md={6} className="p-0 d-none d-md-block">
              <Image
                className="login-banner"
                src={loginBannerImg}
                alt="Login Banner"
              />
            </Col>
          </Row>
        </section>
        <Toaster />
      </main>
    </>
  );
}
